param([string]$build_directory)

$ErrorActionPreference = 'Stop'
$native_root = $PSScriptRoot
$package_root = Split-Path -Parent $native_root
$vswhere_path = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio/Installer/vswhere.exe'
$vs_install = & $vswhere_path -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
if (!$vs_install) { throw 'Visual Studio C++ x64 tools are required.' }
$vcvars_path = Join-Path $vs_install 'VC/Auxiliary/Build/vcvars64.bat'
if ([string]::IsNullOrWhiteSpace($build_directory)) {
    $build_directory = Join-Path ([System.IO.Path]::GetTempPath()) ('d9speed_nvenc_build_' + [guid]::NewGuid().ToString('N'))
}
$build_dir = [System.IO.Path]::GetFullPath($build_directory)
New-Item -ItemType Directory -Force -Path $build_dir | Out-Null
$compile_script = Join-Path $build_dir 'compile.cmd'
$native_source = Join-Path $native_root 'nvenc_gpu.cpp'
$dll_path = Join-Path $build_dir 'd9_nvenc_gpu.dll'
@"
@echo off
call "$vcvars_path" >nul
if errorlevel 1 exit /b 1
cl /nologo /std:c++17 /O2 /EHsc /MT /W4 /LD "$native_source" /Fo"$build_dir\nvenc_gpu.obj" /link /OUT:"$dll_path" /IMPLIB:"$build_dir\nvenc_gpu.lib" d3d11.lib dxgi.lib
if errorlevel 1 exit /b 1
cl /nologo /std:c++17 /O2 /EHsc /MT /W4 "$native_root\native_smoke.cpp" /Fo"$build_dir\native_smoke.obj" /link /OUT:"$build_dir\native_smoke.exe" d3d11.lib dxgi.lib
"@ | Set-Content -LiteralPath $compile_script -Encoding ascii
& $compile_script
if ($LASTEXITCODE -ne 0) { throw 'Native compilation failed.' }
$hash = (Get-FileHash -LiteralPath $dll_path -Algorithm SHA256).Hash.ToLowerInvariant()
$binary_name = 'd9_nvenc_gpu_' + $hash.Substring(0,12)
$plugin_dir = Join-Path $package_root 'Plugins/x86_64'
New-Item -ItemType Directory -Force -Path $plugin_dir | Out-Null
$published_path = Join-Path $plugin_dir ($binary_name + '.dll')
if (!(Test-Path -LiteralPath $published_path)) { Copy-Item -LiteralPath $dll_path -Destination $published_path }
$import_template = Join-Path $native_root 'plugin_importer.meta.template'
if (!(Test-Path -LiteralPath ($published_path + '.meta'))) {
    (Get-Content -LiteralPath $import_template -Raw).Replace('__GUID__', [guid]::NewGuid().ToString('N')) |
        Set-Content -LiteralPath ($published_path + '.meta') -Encoding utf8
}
$build_info = Join-Path $package_root 'Runtime/native_build.cs'
@"
// Generated by native~/build_native.ps1. Content-addressed DLLs permit safe Editor iteration.
namespace D9speed.NvencGpu { internal static class native_build { internal const string dll_name = "$binary_name"; } }
"@ | Set-Content -LiteralPath $build_info -Encoding utf8
Write-Output "Built $published_path"
Write-Output "SHA256 $hash"
