// Generated by native~/build_native.ps1. Content-addressed DLLs permit safe Editor iteration.
namespace D9speed.NvencGpu { internal static class native_build { internal const string dll_name = "d9_nvenc_gpu_1c3d4cda56ad"; } }
